"""create_all_tables

Revision ID: 001
Revises:
Create Date: 2026-04-16 21:09:26.262662
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "001"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clientes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("documento", sa.String(length=255), nullable=False),
        sa.Column("documento_hash", sa.String(length=64), nullable=False),
        sa.Column("tipo_documento", sa.String(length=4), nullable=False),
        sa.Column("contato", sa.String(length=255), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("documento_hash"),
    )
    op.create_table(
        "itens_estoque",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column(
            "preco_unitario_valor", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("preco_unitario_moeda", sa.String(length=3), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "servicos_oferecidos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("preco_valor", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("preco_moeda", sa.String(length=3), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tokens_revogados",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("jti", sa.String(length=255), nullable=False),
        sa.Column("revogado_em", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tokens_revogados_jti"), "tokens_revogados", ["jti"], unique=True
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("senha_hash", sa.String(length=255), nullable=False),
        sa.Column("papel", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "consentimentos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cliente_id", sa.Uuid(), nullable=False),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("concedido_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revogado_em", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["cliente_id"], ["clientes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "veiculos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("placa", sa.String(length=7), nullable=False),
        sa.Column("marca", sa.String(length=100), nullable=False),
        sa.Column("modelo", sa.String(length=100), nullable=False),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("cliente_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clientes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("placa"),
    )
    op.create_table(
        "ordens_de_servico",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cliente_id", sa.Uuid(), nullable=False),
        sa.Column("veiculo_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("orcamento_json", sa.Text(), nullable=True),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clientes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["veiculo_id"],
            ["veiculos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "itens_da_ordem",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ordem_id", sa.Uuid(), nullable=False),
        sa.Column("servico_catalogo_id", sa.Uuid(), nullable=False),
        sa.Column("item_estoque_id", sa.Uuid(), nullable=True),
        sa.Column("descricao", sa.String(length=255), nullable=False),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column(
            "preco_unitario_valor", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("preco_unitario_moeda", sa.String(length=3), nullable=False),
        sa.ForeignKeyConstraint(
            ["ordem_id"], ["ordens_de_servico.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("itens_da_ordem")
    op.drop_table("ordens_de_servico")
    op.drop_table("veiculos")
    op.drop_table("consentimentos")
    op.drop_table("usuarios")
    op.drop_index(op.f("ix_tokens_revogados_jti"), table_name="tokens_revogados")
    op.drop_table("tokens_revogados")
    op.drop_table("servicos_oferecidos")
    op.drop_table("itens_estoque")
    op.drop_table("clientes")
    # ### end Alembic commands ###
